---
- hosts: web
  become: true

  tasks:
  - name: install git
    yum:
      name: git
      state: present

  - name: install wget
    yum:
      name: wget
      state: present

  - name: install unzip
    yum:
      name: git
      state: present

  - name: install vim
    yum:
      name: vim
      state: present

  - name: install java-1.8.0*
    yum:
      name: java-1.8.0*
      state: latest

  - name: download tomcat
    get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
        dest: /home/centos
    become: no
  - name: unarchive tomcat
    unarchive:
         src: /home/centos/apache-tomcat-7.0.94.tar.gz
         dest: /home/centos/
         remote_src: true
    become: no
  - name: port for tomcat -8080
    shell: "/home/centos/apache-tomcat-7.0.94/bin/startup.sh"
    become: no
